<?php

use Illuminate\Database\Seeder;

class DepartmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    DB::table('departments')->insert([
		    ['name' => 'GRAFIČKO LIKOVNO UREDNIŠTVO'],
		    ['name' => 'GRUPA NA RECEPCIJU'],
		    ['name' => 'GRUPA PROMOTORA I'],
		    ['name' => 'GRUPA PROMOTORA II'],
		    ['name' => 'GRUPA PROMOTORA III'],
		    ['name' => 'GRUPA PROMOTORA IV'],
		    ['name' => 'GRUPA PROMOTORA V'],
		    ['name' => 'GRUPA PROMOTORA VI'],
		    ['name' => 'GRUPA PROMOTORA VII'],
		    ['name' => 'GRUPA PROMOTORA VIII'],
		    ['name' => 'GRUPA PROMOTORA X'],
		    ['name' => 'GRUPA ZA ADMINISTRACIJU'],
		    ['name' => 'GRUPA ZA ČASOPISE (Modra Lasta)'],
			['name' => 'GRUPA ZA ČASOPISE (Smib)'],
		    ['name' => 'GRUPA ZA FINANCIJSKU OPERATIVU'],
		    ['name' => 'GRUPA ZA IZLAZ'],
		    ['name' => 'GRUPA ZA KONTROLU'],
		    ['name' => 'GRUPA ZA KOREKTURU'],
		    ['name' => 'GRUPA ZA LEKTURU'],
		    ['name' => 'GRUPA ZA MARKETINŠKA DOGAĐANJA'],
		    ['name' => 'GRUPA ZA NABAVU'],
		    ['name' => 'GRUPA ZA OBRAČUN PLAĆA'],
		    ['name' => 'GRUPA ZA ODRŽAVANJE'],
		    ['name' => 'GRUPA ZA ODRŽAVANJE I KUHINJA'],
		    ['name' => 'GRUPA ZA PISARNICU'],
		    ['name' => 'GRUPA ZA PODRŠKU KOMERCIJALI'],
		    ['name' => 'GRUPA ZA PODRŠKU MARKETINGU'],
		    ['name' => 'GRUPA ZA PODRŠKU NAKLADNIŠTVU'],
		    ['name' => 'GRUPA ZA SKLADIŠTE'],
		    ['name' => 'GRUPA ZA TERENSKU I INOZEMNU PRODAJU'],
		    ['name' => 'GRUPA ZA VOZNI PARK'],
		    ['name' => 'GRUPE ZA NABAVU, OPĆE i TEHNIČKE POSLOVE'],
		    ['name' => 'IZVRŠNO UREDNIŠTVO ŠKOLSKOG PROGRAMA III'],
		    ['name' => 'IZVRŠNO UREDNIŠTVO ZVAN ŠKOLSKOG PROGRAMA'],
		    ['name' => 'KNJIŽARA ARKADIJA'],
		    ['name' => 'KNJIŽARA BJELOVAR'],
		    ['name' => 'KNJIŽARA BOGOVIĆEVA'],
		    ['name' => 'KNJIŽARA ČAKOVEC'],
		    ['name' => 'KNJIŽARA DUBROVNIK'],
		    ['name' => 'KNJIŽARA FFZG'],
		    ['name' => 'KNJIŽARA GOSPIĆ'],
		    ['name' => 'KNJIŽARA ILICA'],
		    ['name' => 'KNJIŽARA IMOTSKI'],
		    ['name' => 'KNJIŽARA KARLOVAC'],
		    ['name' => 'KNJIŽARA KVATRIĆ'],
		    ['name' => 'KNJIŽARA MAKARSKA'],
		    ['name' => 'KNJIŽARA MASARYKOVA P2'],
		    ['name' => 'KNJIŽARA MASARYKOVA P3'],
		    ['name' => 'KNJIŽARA METKOVIĆ'],
		    ['name' => 'KNJIŽARA OGULIN'],
		    ['name' => 'KNJIŽARA OSIJEK'],
		    ['name' => 'KNJIŽARA POŽEGA'],
		    ['name' => 'KNJIŽARA PULA'],
		    ['name' => 'KNJIŽARA RIJEKA'],
		    ['name' => 'KNJIŽARA SINJ'],
		    ['name' => 'KNJIŽARA SISAK'],
		    ['name' => 'KNJIŽARA SPLIT'],
		    ['name' => 'KNJIŽARA VARAŽDIN P12'],
		    ['name' => 'KNJIŽARA VARAŽDIN P17'],
		    ['name' => 'KNJIŽARA VINKOVCI'],
		    ['name' => 'KNJIŽARA VUKOVAR'],
		    ['name' => 'KNJIŽARA ZADAR'],
		    ['name' => 'KNJIŽARA ZAPREŠIĆ'],
		    ['name' => 'ODJEL PRODUKCIJE'],
		    ['name' => 'ODJEL RAZVOJA I MARKETINGA ZA REGIJU'],
		    ['name' => 'ODJEL ZA FINANCIJE I RAČUNOVODSTVO'],
		    ['name' => 'ODJEL ZA LOGISTIKU'],
		    ['name' => 'ODJEL ZA ODNOSE S AUTORIMA'],
		    ['name' => 'ODJEL ZA PROMOCIJU U REGIJI'],
		    ['name' => 'ODJEL ZA VELEPRODAJU, DIREKTNU I INOZEMNU PRODAJU'],
		    ['name' => 'ODSJEK DIZAJNA'],
		    ['name' => 'ODSJEK IZVRŠNOG UREDNIŠTVA I'],
		    ['name' => 'ODSJEK IZVRŠNOG UREDNIŠTVA II'],
		    ['name' => 'ODSJEK IZVRŠNOG UREDNIŠTVA III'],
		    ['name' => 'ODSJEK MULTIMEDIJE'],
		    ['name' => 'ODSJEK RAZVOJA I MARKETINGA'],
		    ['name' => 'ODSJEK UREDNIŠTVA I ČASOPISA (RAZVOJ SADRŽAJA)'],
			['name' => 'ODSJEK ZA DIREKTNU PRODAJU'],
		    ['name' => 'ODSJEK ZA FINANCIJE I RAČUNOVODSVO'],
		    ['name' => 'ODSJEK ZA INFORMATIKU'],
		    ['name' => 'ODSJEK ZA KONTROLING'],
		    ['name' => 'ODSJEK ZA LJUDSKE POTENCIJALE'],
		    ['name' => 'ODSJEK ZA MALOPRODAJU'],
		    ['name' => 'ODSJEK ZA MARKETINŠKE KOMUNIKACIJE'],
		    ['name' => 'ODSJEK ZA PODRŠKU VELEPRODAJI'],
		    ['name' => 'ODSJEK ZA PRAVNE POSLOVE'],
		    ['name' => 'ODSJEK ZA SKLADIŠTE'],
		    ['name' => 'ODSJEK ZA ZA PODRŠKU MALOPRODAJI'],
		    ['name' => 'SEKTOR KOMERCIJALE'],
		    ['name' => 'SEKTOR NAKLADNIŠTVA'],
		    ['name' => 'TAJNIŠTVO UPRAVE I NADZORNOG ODBORA'],
		    ['name' => 'UPRAVA'],
	    ]);
    }
}
